Output form-validation.gif

Hide
Type "go build -o form-validation ."
Enter
Type "clear"
Enter
Show

Type "Start-Process -FilePath .\form-validation -Wait -NoNewWindow"
Enter
Sleep 0.5

Type "rainbowjelly23"
Sleep 0.5
Enter
Type "Db1d$wctP!"
Sleep 0.5
Enter
Type "Db1d$wctP!"
Sleep 0.5
Enter
Type "rj23@charmcli.com"
Sleep 0.5
Enter
Type "rj"
Sleep 0.5
Enter
Sleep 1

Hide
Ctrl+C
Type "rm form-validation"
Enter